# Generated by Django 5.1.1 on 2024-09-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_tag_book_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="author",
            name="last_name",
            field=models.CharField(default="first name", max_length=100),
            preserve_default=False,
        ),
    ]
