# Generated by Django 5.1.1 on 2024-09-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_auto_20240917_1230"),
    ]

    operations = [
        migrations.CreateModel(
            name="HttpRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user", models.CharField(blank=True, max_length=100, null=True)),
                ("remote_addr", models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"permissions": [("can_edit_book", "Can edit book")]},
        ),
    ]
