# Generated by Django 5.1.1 on 2024-09-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("genre", models.CharField(max_length=100)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("count", models.IntegerField()),
            ],
        ),
    ]
