# Generated by Django 5.1.1 on 2024-09-17 12:30
from django.db import migrations

def add_specific_book(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    Tag = apps.get_model('books', 'Tag')

    book = Book.objects.create(
        store="Example Store",
        title="Specific Book Title",
        genre="Fiction",
        isbn="2234567890123",
        price=19.99,
        count=10,
    )

    tag, _created = Tag.objects.get_or_create(name='tag_not_set')
    book.tags.add(tag)

def remove_specific_book(apps, schema_editor):
    Book = apps.get_model('books', 'Book')

    Book.objects.filter(isbn="2234567890123").delete()

class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_rename_name_author_first_name_author_last_name"),
    ]

    operations = [
        migrations.RunPython(add_specific_book, remove_specific_book),
    ]

# migrate - python manage.py migrate
# rollback
#  0004_rename_name_author_first_name_author_last_name