# Generated by Django 5.1.1 on 2024-09-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_httprequestlog_alter_book_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publish_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
